version: 2
updates:
  - package-ecosystem: "npm"
    directory: "Build/" # Location of your package.json and package-lock.json files
    schedule:
      interval: "weekly" # How often Dependabot checks for updates (e.g., daily, weekly, monthly)
    target-branch: "dev"
    labels:
      - "dependencies"
      - "npm"
