//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureFunctions.ResourcesBinding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceBinding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceBinding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureFunctions.ResourcesBinding.ResourceBinding", typeof(ResourceBinding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the connection string for your event hub. Make sure that it has Send permissions..
        /// </summary>
        internal static string eventHubOut_connection_label {
            get {
                return ResourceManager.GetString("eventHubOut_connection_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Hub connection.
        /// </summary>
        internal static string eventHubOut_connection_label1 {
            get {
                return ResourceManager.GetString("eventHubOut_connection_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Event Hub.
        /// </summary>
        internal static string eventHubOut_displayName {
            get {
                return ResourceManager.GetString("eventHubOut_displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the parameter in the code for output binding to bind to..
        /// </summary>
        internal static string eventHubOut_name_help {
            get {
                return ResourceManager.GetString("eventHubOut_name_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event parameter name.
        /// </summary>
        internal static string eventHubOut_name_label {
            get {
                return ResourceManager.GetString("eventHubOut_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your event hub name must start and end with a letter or number, and it can contain only lowercase letters, numbers, the period, the hyphen, and the underscore..
        /// </summary>
        internal static string eventHubOut_path_errorText {
            get {
                return ResourceManager.GetString("eventHubOut_path_errorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the event hub to which the event will be sent..
        /// </summary>
        internal static string eventHubOut_path_help {
            get {
                return ResourceManager.GetString("eventHubOut_path_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Hub name.
        /// </summary>
        internal static string eventHubOut_path_label {
            get {
                return ResourceManager.GetString("eventHubOut_path_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the connection string for your event hub. Make sure that it has Receive permissions..
        /// </summary>
        internal static string eventHubTrigger_connection_help {
            get {
                return ResourceManager.GetString("eventHubTrigger_connection_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Hub connection.
        /// </summary>
        internal static string eventHubTrigger_connection_label {
            get {
                return ResourceManager.GetString("eventHubTrigger_connection_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Event Hub consumer group to receive events from..
        /// </summary>
        internal static string eventHubTrigger_consumerGroup_help {
            get {
                return ResourceManager.GetString("eventHubTrigger_consumerGroup_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Hub consumer group.
        /// </summary>
        internal static string eventHubTrigger_consumerGroup_label {
            get {
                return ResourceManager.GetString("eventHubTrigger_consumerGroup_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Event Hub.
        /// </summary>
        internal static string eventHubTrigger_displayName {
            get {
                return ResourceManager.GetString("eventHubTrigger_displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the parameter in the code for trigger to bind to..
        /// </summary>
        internal static string eventHubTrigger_name_help {
            get {
                return ResourceManager.GetString("eventHubTrigger_name_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event parameter name.
        /// </summary>
        internal static string eventHubTrigger_name_label {
            get {
                return ResourceManager.GetString("eventHubTrigger_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your event hub name must start and end with a letter or number, and it can contain only lowercase letters, numbers, the hyphen, the period, and the underscore..
        /// </summary>
        internal static string eventHubTrigger_path_errorText {
            get {
                return ResourceManager.GetString("eventHubTrigger_path_errorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the event hub you would like to trigger off of..
        /// </summary>
        internal static string eventHubTrigger_path_help {
            get {
                return ResourceManager.GetString("eventHubTrigger_path_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Hub name.
        /// </summary>
        internal static string eventHubTrigger_path_label {
            get {
                return ResourceManager.GetString("eventHubTrigger_path_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Storage Queue.
        /// </summary>
        internal static string queueOut_displayName {
            get {
                return ResourceManager.GetString("queueOut_displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the parameter in the code for output binding to bind to..
        /// </summary>
        internal static string queueOut_name_help {
            get {
                return ResourceManager.GetString("queueOut_name_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message parameter name.
        /// </summary>
        internal static string queueOut_name_label {
            get {
                return ResourceManager.GetString("queueOut_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your queue name must start and end with a letter or number, and it can contain only lowercase letters, numbers, and the hyphen. The name must be 3 to 63 characters..
        /// </summary>
        internal static string queueOut_queueName_erroText {
            get {
                return ResourceManager.GetString("queueOut_queueName_erroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue name.
        /// </summary>
        internal static string queueOut_queueName_label {
            get {
                return ResourceManager.GetString("queueOut_queueName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the queue to which the message will be sent. If the queue doesn&apos;t exist yet, one will be created for you in the specifed storage account..
        /// </summary>
        internal static string queueOut_queueName_name {
            get {
                return ResourceManager.GetString("queueOut_queueName_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        internal static string temp_category_core {
            get {
                return ResourceManager.GetString("temp_category_core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Processing.
        /// </summary>
        internal static string temp_category_dataProcessing {
            get {
                return ResourceManager.GetString("temp_category_dataProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# function that will be run on a specified schedule.
        /// </summary>
        internal static string temp_timerTrigger_CSharp_desc {
            get {
                return ResourceManager.GetString("temp_timerTrigger_CSharp_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimerTrigger - C#.
        /// </summary>
        internal static string temp_timerTrigger_CSharp_name {
            get {
                return ResourceManager.GetString("temp_timerTrigger_CSharp_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string timerTrigger_displayName {
            get {
                return ResourceManager.GetString("timerTrigger_displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the parameter in the code for trigger to bind to..
        /// </summary>
        internal static string timerTrigger_name_help {
            get {
                return ResourceManager.GetString("timerTrigger_name_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp parameter nam.
        /// </summary>
        internal static string timerTrigger_name_label {
            get {
                return ResourceManager.GetString("timerTrigger_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a cron expression of the format &apos;{second} {minute} {hour} {day} {month} {day of week}&apos; to specify your schedule. Please consult the documentation to learn more..
        /// </summary>
        internal static string timerTrigger_schedule_help {
            get {
                return ResourceManager.GetString("timerTrigger_schedule_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string timerTrigger_schedule_label {
            get {
                return ResourceManager.GetString("timerTrigger_schedule_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Name.
        /// </summary>
        internal static string variable_paramNameLabel {
            get {
                return ResourceManager.GetString("variable_paramNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string for your SaaS Table connection.
        /// </summary>
        internal static string variables_apiHubTableConnectionHelp {
            get {
                return ResourceManager.GetString("variables_apiHubTableConnectionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaaS Table connection.
        /// </summary>
        internal static string variables_apiHubTableConnectionLabel {
            get {
                return ResourceManager.GetString("variables_apiHubTableConnectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the data set to bind to.  Leave as &apos;default&apos; if binding to a table or entity..
        /// </summary>
        internal static string variables_apiHubTableDataSetHelp {
            get {
                return ResourceManager.GetString("variables_apiHubTableDataSetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Set Name.
        /// </summary>
        internal static string variables_apiHubTableDataSetLabel {
            get {
                return ResourceManager.GetString("variables_apiHubTableDataSetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the entity to bind to.  Leave empty if binding to a data set or table.
        /// </summary>
        internal static string variables_apiHubTableEntityHelp {
            get {
                return ResourceManager.GetString("variables_apiHubTableEntityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity ID.
        /// </summary>
        internal static string variables_apiHubTableEntityLabel {
            get {
                return ResourceManager.GetString("variables_apiHubTableEntityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the table to bind to.  Leave empty if binding to a data set or entity.
        /// </summary>
        internal static string variables_apiHubTableHelp {
            get {
                return ResourceManager.GetString("variables_apiHubTableHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name.
        /// </summary>
        internal static string variables_apiHubTableNameLabel {
            get {
                return ResourceManager.GetString("variables_apiHubTableNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the connection string for your storage account..
        /// </summary>
        internal static string variables_appSettingsHelp {
            get {
                return ResourceManager.GetString("variables_appSettingsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter name must be an alphanumeric string of any number of characters. It can’t start with a number..
        /// </summary>
        internal static string variables_parameterName {
            get {
                return ResourceManager.GetString("variables_parameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the parameter in code for the input binding to bind to..
        /// </summary>
        internal static string variables_paramNameInputHelp {
            get {
                return ResourceManager.GetString("variables_paramNameInputHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the parameter in code for the output binding to bind to..
        /// </summary>
        internal static string variables_paramNameOutputHelp {
            get {
                return ResourceManager.GetString("variables_paramNameOutputHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click select to choose a connection.
        /// </summary>
        internal static string variables_selectConnection {
            get {
                return ResourceManager.GetString("variables_selectConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account connection.
        /// </summary>
        internal static string variables_storageConnStringLabel {
            get {
                return ResourceManager.GetString("variables_storageConnStringLabel", resourceCulture);
            }
        }
    }
}
